spring:
    application:
        name: duck-simulator
    datasource:
        url: jdbc:mysql://localhost:3307/duck_db?createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
        password: root123
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: false
    flyway:
        enabled: true
        baseline-on-migrate: true
        validate-on-migrate: true
        locations: classpath:db/migration
        user: root
        password: root123
        baseline-version: 1